### ISSUE TITLE
Add dependency library plz...!

### ISSUE THREAD

**Issue by sivasakthic** [Nuxar1/PUBG-Decrypt-Dumper#2]

**Comment by S1ckZer** [comment]
Prerequisites:

CMake: Necessary for building Zydis. Download and install CMake if you haven't already.
Doxygen: Required for generating documentation. Download and install Doxygen.

Clone&Build Zydis and Zycore:

git clone --recursive https://github.com/zyantific/zydis.git
cd zydis
cmake -B build
cmake --build build -j4

After Building:

In the build folder, you'll find Zydis.c, Zydis.h, and Zydis.lib.

Integrate Zydis into Your Dumper Project:

Copy Zydis.c, Zydis.h, and Zydis.lib to your project's appropriate directory.
Set up your project properties to include Zydis as part of your build, ensuring the include and library paths are correctly set to where you've placed Zydis.h and Zydis.lib.

Build Your Dumper Project!


https://doc.zydis.re/master/html/

**Comment by Nuxar1** [comment]
Cmake isn't needed anymore Zydis added an msvc build system. Just clone using visual studio, select release and then build it. After that add the paths to the dumper project.
