### ISSUE TITLE
Failed to find decryptors

### ISSUE THREAD

**Issue by houba-linko** [Nuxar1/PUBG-Decrypt-Dumper#3]
PUBG-Decrypt-Dumper.exe F:\SteamLibrary\steamapps\common\PUBG\TslGame\Binaries\Win64\TslGame.exe
Failed to find decryptors

what should i do ? 
<3

**Comment by Nuxar1** [comment]
dump the game and pass that file to the program.

**Comment by houba-linko** [comment]
ty
